#! /bin/sh
# /etc/init.d/vision

### BEGIN INIT INFO
# Provides:          vision
# Required-Start:    avahi-daemon
# Required-Stop:     avahi-daemon
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Wrapper script to launch the vision software
# Description:       The vision software should be built before booting (or
#                    starting the daemon).
### END INIT INFO

### INSTALL PROCESS ###
#1) Copy this script to /etc/init.d/vision
#2) Reload service with 'sudo systemctl daemon-reload'
#3) Enable the service with 'sudo systemctl enable vision'
#4) Launch service with 'sudo systemctl start vision'

# Verify the status of the service with 'systemctl status vision'

### REBUILD/UPGRADE ###
#1) Build new code with './gradlew build'
#2) Relaunch service with 'sudo systemctl restart vision'

### STOPPING ###
#1) Temporarily stop service with 'sudo systemctl stop vision'

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting robot vision software"
    cd /home/pi/RaspberryPi/output
    chmod +x runCameraVision
    ./runCameraVision > vision.log 2>vision.err &
    ;;
  stop)
    echo "Stopping robot vision software"
    # TODO: use proper pid-file to cleanly stop the vision processor
    kill -9 $(ps -efa | grep Camera | grep java | tr -s ' ' | cut -d' ' -f2)
    ;;
  *)
    echo "Usage: /etc/init.d/vision {start|stop}"
    exit 1
    ;;
esac

exit 0
